sylius_grid:
    grids:
        macbim_sylius_gift_cards_admin_gift_card_channel_configuration:
            driver:
                name: doctrine/orm
                options:
                    class: '%macbim_sylius_gift_cards.model.gift_card_channel_configuration.class%'
                    repository:
                        method: createListQueryBuilder
            sorting:
                id: desc
            fields:
                id:
                    type: string
                    enabled: false
                    sortable: ~
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
