sylius_grid:
    grids:
        macbim_sylius_gift_cards_admin_gift_card_channel_configuration:
            driver:
                name: doctrine/orm
                options:
                    class: '%macbim_sylius_gift_cards.model.gift_card_channel_configuration.class%'
                    repository:
                        method: createListQueryBuilder
            sorting:
                code: desc
            filters:
                code:
                    type: string
                    label: sylius.ui.code
                channel:
                    type: entity
                    label: sylius.ui.channel
                    form_options:
                        class: "%sylius.model.channel.class%"
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                channel:
                    type: twig
                    label: sylius.ui.channel
                    options:
                        template: "@MacbimSyliusGiftCardsPlugin/Admin/GiftCardChannelConfiguration/Grid/Field/channel.html.twig"
                expirationDelay:
                    type: string
                    label: macbim_sylius_gift_cards.ui.expiration_delay
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
