imports:
    - { resource: 'services.php' }
    - { resource: 'grids/*.yaml' }
    - { resource: 'state_machine/*.yaml' }

sylius_ui:
    events:
        macbim_sylius_gift_cards.admin.product.tab_gift_card_content:
            blocks:
                form:
                    template: '@MacbimSyliusGiftCardsPlugin/Admin/Product/Tab/_giftCardContent.html.twig'
        
        sylius.admin.order.show.summary:
            blocks:
                created_gift_cards:
                    template: '@MacbimSyliusGiftCardsPlugin/Admin/Order/Show/_giftCardSummary.html.twig'
